### ISSUE TITLE
Bot didnt sent a message.

### ISSUE THREAD

**Issue by ghost** [nanato12/pylinebot#3]
From op, i try all method, with image, sticker video etc
but bot didnt response why?

**Comment by nanato12** [comment]
@Baka-nee 
I just checked that `pylinebot` is no problems.

Please check "use webhook".
If it is disabled, enable it.

<kbd><img width="403" alt="linebot use-webhook" src="https://user-images.githubusercontent.com/49806926/85504337-c9ddf300-b626-11ea-8154-ce9f24401ccb.png"></kbd>


Please enter the URL to receive the event.
<kbd><img width="433" alt="webhook-url" src="https://user-images.githubusercontent.com/49806926/85504947-1544d100-b628-11ea-9e52-6d2e006e69a6.png">
</kbd>


And if you use in groups, enable this.
<kbd><img width="979" alt="linebot use-group" src="https://user-images.githubusercontent.com/49806926/85504625-5dafbf00-b627-11ea-860f-2f59638b316c.png"></kbd>


https://developers.line.biz/console/

**Comment by ghost** [comment]
am deploy to heroku bro, the response ok, but bot didnt sent message as i
command it.

**Comment by nanato12** [comment]
@Baka-nee 
Please show me source code.

**Comment by ghost** [comment]
Line id or email

**Comment by nanato12** [comment]
@Baka-nee 
Please send me `admin@nanato12.info`

**Comment by nanato12** [comment]
@Baka-nee 
Sorry, `pylinebot` has a problem.
Fix now.
Thank you.

**Comment by ghost** [comment]
thank you, i need more help, can i get your line id?

Pada tanggal Rab, 24 Jun 2020 15.21, ななといつ <notifications@github.com>
menulis:

**Comment by nanato12** [comment]
@Baka-nee 
ok, I sent email.
